<?php

namespace AppBundle\Repository;

/**
 * AppointementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointementRepository extends \Doctrine\ORM\EntityRepository
{
}
