<?php

namespace AppBundle\Repository;

/**
 * PromoCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoCreditRepository extends \Doctrine\ORM\EntityRepository
{
}
