<?php

namespace AppBundle\Repository;

/**
 * ServiceCatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCatalogRepository extends \Doctrine\ORM\EntityRepository
{
}
