<?php

namespace AppBundle\Repository;

/**
 * ServiceListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceListRepository extends \Doctrine\ORM\EntityRepository
{
}
