<?php

namespace AppBundle\Repository;

/**
 * StripeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripeRepository extends \Doctrine\ORM\EntityRepository
{
}
