<?php

namespace AppBundle\Repository;

/**
 * TeamMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
