security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
      ROLE_ADMIN:    [ROLE_SUPER_ADMIN, ROLE_ADD_ADMIN, ROLE_BACK_ACCESS]
      ROLE_CLIENT:   [ROLE_USER, ROLE_FRONT_ACCESS]
      ROLE_TEAM:   [ROLE_BACK_ACCESS, ROLE_FRONT_ACCESS]

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        urmet:
            pattern:   ^/login/urmet
            context: main
            http_basic: ~
            provider: fos_userbundle
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login

            remember_me:
                secret:      '%secret%'
                lifetime: 604800
                path:     /
                domain:   ~
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_BACK_ACCESS, ROLE_SUPER_ADMIN] }
        - { path: ^/user/, role: ROLE_FRONT_ACCESS }
        - { path: /, roles: [ROLE_BACK_ACCESS, ROLE_FRONT_ACCESS] }
