GROUP_ADMIN:
  - ROLE_BACK_ACCESS
  - ROLE_ADD_ADMIN
  - ROLE_ADMIN


GROUP_COIFFEUR:
  - ROLE_BACK_ACCESS
  - ROLE_FRONT_ACCESS
  - ROLE_MANAGE_CLIENT


GROUP_CLIENT:
  - ROLE_FRONT_ACCESS
  - ROLE_USER
