services:
    app.analytics:
        class: AppBundle\Utils\AppAnalytics
        arguments: ["@doctrine"]

    app.email.sender:
        class: Appbundle\utils\EmailSender
        arguments: ["@doctrine", "@mailer", "@templating", "@logger", "%default_from_email%"]
