app_api_default:
    type: rest
    ressource:    "ApiBundle:ApiDefault"
    name_prefix:  api_

app_api_add_manager:
    type: rest
    ressource:    "ApiBundle:ApiAddManager"
    name_prefix:  api_
